### Adicionar um cliente
POST http://localhost:9090/druuls/api/rule
Content-Type:application/json

{
  "id" : 1,
  "values" : {
    "Cenario" : "501",
    "Nome" : "davi"
  }
}

### Ler
#GET http://localhost:9090/druuls/
#Content-Type:application/json

###
