/*
 * MIT License
 *
 * Copyright (c) 2018 Davi Saranszky Mesquita
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package test;
import com.github.frkr.druuls.dao.Entrada
import com.github.frkr.druuls.dao.Saida

// DECLARAR TODOS OS TIPOS
declare  Perfil
    Nome : String
    Cenario : Integer
end

declare Aprovacao
    Cenario : Integer
    Aprovado : Boolean
end

rule "Entrada"
no-loop
    when
        entrada : Entrada()
    then
        // PEGAR TODOS OS VALORES DA ENTRADA
        // INICIALIZAR TODOS OS TIPOS
        Perfil perfil = new Perfil();
        perfil.setNome(entrada.getValues().get("Nome"));
        perfil.setCenario( Integer.parseInt( entrada.getValues().get("Cenario") ) );
        insert(perfil);
        Aprovacao aprovacao = new Aprovacao();
        aprovacao.setCenario(null);
        aprovacao.setAprovado(false);
        insert(aprovacao);
end

rule "Saida"
no-loop
    when
        saida : Saida()
        v : Aprovacao()
    then
        // ESCOLHER UM TIPO PARA SER A SAIDA
        saida.getValues().put("Cenario", v.getCenario()+"");
        saida.getValues().put("Aprovado", v.getAprovado()+"");
        update(saida);
end

// COLOCAR UMA OU MAIS REGRAS DE USUARIO

rule "Regra do Usuario"
no-loop
    when
        perfil : Perfil( Cenario > 500 )
        aprovacao : Aprovacao()
    then
        aprovacao.setCenario(perfil.getCenario());
        aprovacao.setAprovado(true);
        update(aprovacao);
end
